#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Fri May 15 23:15:29 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ConfigIgnore(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConfigIgnore.__init__
        wx.Panel.__init__(self, *args, **kwds)
        self.checkbox_hidden = wx.CheckBox(self, wx.ID_ANY, _("Hidden Files"))
        self.checkbox_cvs = wx.CheckBox(self, wx.ID_ANY, _("Version Control Directories: CVS, .svn, .git, .hg"))
        self.checkbox_user_dir = wx.CheckBox(self, wx.ID_ANY, _("User Defined Directories"))
        self.checkbox_user_filetype = wx.CheckBox(self, wx.ID_ANY, _("User Defined File Types"))
        self.sizer_4_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Ignore These Directories and Files"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ConfigIgnore.__set_properties
        self.SetSize((758, 535))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConfigIgnore.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_4_staticbox.Lower()
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.VERTICAL)
        sizer_4.Add(self.checkbox_hidden, 0, 0, 0)
        sizer_4.Add(self.checkbox_cvs, 0, 0, 0)
        sizer_4.Add(self.checkbox_user_dir, 0, 0, 0)
        sizer_4.Add(self.checkbox_user_filetype, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

# end of class ConfigIgnore
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        config = ConfigIgnore(None, wx.ID_ANY, "")
        self.SetTopWindow(config)
        config.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    gettext.install("BookMateConfig") # replace with the appropriate catalog name

    BookMateConfig = MyApp(0)
    BookMateConfig.MainLoop()