#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Fri May 15 23:17:23 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class DuplicateKeep(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DuplicateKeep.__init__
        wx.Panel.__init__(self, *args, **kwds)
        self.radio_box_1_copy_copy = wx.RadioBox(self, wx.ID_ANY, _("Keep One Copy"), choices=[_("File with longest name"), _("The oldest"), _("File in less layers of directories"), _("File in more layers of directories"), _("Any one is OK. Don't care anything else")], majorDimension=1, style=wx.RA_SPECIFY_COLS)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DuplicateKeep.__set_properties
        self.SetSize((758, 535))
        self.radio_box_1_copy_copy.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DuplicateKeep.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.radio_box_1_copy_copy, 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class DuplicateKeep
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        config = DuplicateKeep(None, wx.ID_ANY, "")
        self.SetTopWindow(config)
        config.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    gettext.install("BookMateConfig") # replace with the appropriate catalog name

    BookMateConfig = MyApp(0)
    BookMateConfig.MainLoop()