#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Tue May  5 22:31:12 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.bookmate = wx.Notebook(self, wx.ID_ANY)
        self.bookmate_config_panel = wx.Panel(self.bookmate, wx.ID_ANY)
        self.label_search_path1 = wx.StaticText(self.bookmate_config_panel, wx.ID_ANY, _("Search Path 1:"), style=wx.ALIGN_RIGHT)
        self.button_path1 = wx.Button(self.bookmate_config_panel, wx.ID_ANY, _("Browse"))
        self.text_ctrl_1 = wx.TextCtrl(self.bookmate_config_panel, wx.ID_ANY, "")
        self.label_search_path2 = wx.StaticText(self.bookmate_config_panel, wx.ID_ANY, _("Search Path 2:"), style=wx.ALIGN_RIGHT)
        self.button_path2 = wx.Button(self.bookmate_config_panel, wx.ID_ANY, _("Browse"))
        self.text_ctrl_2 = wx.TextCtrl(self.bookmate_config_panel, wx.ID_ANY, "")
        self.label_search_path3 = wx.StaticText(self.bookmate_config_panel, wx.ID_ANY, _("Search Path 3:"), style=wx.ALIGN_RIGHT)
        self.button_path3 = wx.Button(self.bookmate_config_panel, wx.ID_ANY, _("Browse"))
        self.text_ctrl_3 = wx.TextCtrl(self.bookmate_config_panel, wx.ID_ANY, "")
        self.label_search_path4 = wx.StaticText(self.bookmate_config_panel, wx.ID_ANY, _("Search Path 4:"), style=wx.ALIGN_RIGHT)
        self.button_path4 = wx.Button(self.bookmate_config_panel, wx.ID_ANY, _("Browse"))
        self.text_ctrl_4 = wx.TextCtrl(self.bookmate_config_panel, wx.ID_ANY, "")
        self.label_exclude_path1 = wx.StaticText(self.bookmate_config_panel, wx.ID_ANY, _("Exclude Path 1:"), style=wx.ALIGN_RIGHT)
        self.button_expath1 = wx.Button(self.bookmate_config_panel, wx.ID_ANY, _("Browse"))
        self.text_ctrl_expath1 = wx.TextCtrl(self.bookmate_config_panel, wx.ID_ANY, "")
        self.label_exclude_path2 = wx.StaticText(self.bookmate_config_panel, wx.ID_ANY, _("Exclude Path 2:"), style=wx.ALIGN_RIGHT)
        self.button_expath2 = wx.Button(self.bookmate_config_panel, wx.ID_ANY, _("Browse"))
        self.text_ctrl_expath2 = wx.TextCtrl(self.bookmate_config_panel, wx.ID_ANY, "")
        self.static_line_1 = wx.StaticLine(self.bookmate_config_panel, wx.ID_ANY, style=wx.EXPAND)
        self.checkbox_hidden = wx.CheckBox(self.bookmate_config_panel, wx.ID_ANY, _("Hidden Files"))
        self.checkbox_cvs = wx.CheckBox(self.bookmate_config_panel, wx.ID_ANY, _("Version Control Directories: CVS, .svn, .git, .hg"))
        self.checkbox_user_dir = wx.CheckBox(self.bookmate_config_panel, wx.ID_ANY, _("User Defined Directories"))
        self.checkbox_user_filetype = wx.CheckBox(self.bookmate_config_panel, wx.ID_ANY, _("User Defined File Types"))
        self.sizer_4_staticbox = wx.StaticBox(self.bookmate_config_panel, wx.ID_ANY, _("Ignore These Directories and Files"))
        self.bookmate_duplicate_panel = wx.Panel(self.bookmate, wx.ID_ANY)
        self.bookmate_rename_panel = wx.Panel(self.bookmate, wx.ID_ANY)
        self.bookmate_extract_panel = wx.Panel(self.bookmate, wx.ID_ANY)
        self.bookmate_same_name_panel = wx.Panel(self.bookmate, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((758, 535))
        self.static_line_1.Hide()
        self.bookmate.SetMinSize((549, 406))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_4_staticbox.Lower()
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_path = wx.FlexGridSizer(6, 3, 0, 0)
        grid_sizer_path.Add(self.label_search_path1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        grid_sizer_path.Add(self.button_path1, 0, wx.RIGHT, 5)
        grid_sizer_path.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        grid_sizer_path.Add(self.label_search_path2, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        grid_sizer_path.Add(self.button_path2, 0, wx.RIGHT, 5)
        grid_sizer_path.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)
        grid_sizer_path.Add(self.label_search_path3, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        grid_sizer_path.Add(self.button_path3, 0, wx.RIGHT, 5)
        grid_sizer_path.Add(self.text_ctrl_3, 0, wx.EXPAND, 0)
        grid_sizer_path.Add(self.label_search_path4, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        grid_sizer_path.Add(self.button_path4, 0, wx.RIGHT, 5)
        grid_sizer_path.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        grid_sizer_path.Add(self.label_exclude_path1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        grid_sizer_path.Add(self.button_expath1, 0, wx.RIGHT, 5)
        grid_sizer_path.Add(self.text_ctrl_expath1, 0, wx.EXPAND, 0)
        grid_sizer_path.Add(self.label_exclude_path2, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        grid_sizer_path.Add(self.button_expath2, 0, wx.RIGHT, 5)
        grid_sizer_path.Add(self.text_ctrl_expath2, 0, wx.EXPAND, 0)
        grid_sizer_path.AddGrowableCol(2)
        sizer_2.Add(grid_sizer_path, 1, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_4.Add(self.checkbox_hidden, 0, 0, 0)
        sizer_4.Add(self.checkbox_cvs, 0, 0, 0)
        sizer_4.Add(self.checkbox_user_dir, 0, 0, 0)
        sizer_4.Add(self.checkbox_user_filetype, 0, 0, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        self.bookmate_config_panel.SetSizer(sizer_1)
        self.bookmate.AddPage(self.bookmate_config_panel, _("config"))
        self.bookmate.AddPage(self.bookmate_duplicate_panel, _("duplicate"))
        self.bookmate.AddPage(self.bookmate_rename_panel, _("rename"))
        self.bookmate.AddPage(self.bookmate_extract_panel, _("extract"))
        self.bookmate.AddPage(self.bookmate_same_name_panel, _("same name"))
        sizer_3.Add(self.bookmate, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

# end of class MyFrame1
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_2 = MyFrame1(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_2)
        frame_2.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    gettext.install("BookMate") # replace with the appropriate catalog name

    BookMate = MyApp(0)
    BookMate.MainLoop()