#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Fri May 15 23:18:59 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ReName(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ReName.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Panel.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Choose File Type:"))
        self.checkbox_1 = wx.CheckBox(self, wx.ID_ANY, _("pdf"))
        self.checkbox_2 = wx.CheckBox(self, wx.ID_ANY, _("epub"))
        self.checkbox_3 = wx.CheckBox(self, wx.ID_ANY, _("mobi"))
        self.checkbox_4 = wx.CheckBox(self, wx.ID_ANY, _("Every files"))
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("Add"))
        self.text_ctrl_6 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("to"))
        self.radio_btn_2 = wx.RadioButton(self, wx.ID_ANY, _("start"), style=wx.RB_GROUP)
        self.radio_btn_3 = wx.RadioButton(self, wx.ID_ANY, _("end (before file type)"))
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _("Remove"))
        self.text_ctrl_7 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("from"))
        self.radio_btn_4 = wx.RadioButton(self, wx.ID_ANY, _("start"), style=wx.RB_GROUP)
        self.radio_btn_5 = wx.RadioButton(self, wx.ID_ANY, _("end"))
        self.radio_btn_6 = wx.RadioButton(self, wx.ID_ANY, _("anywhere"))
        self.label_6 = wx.StaticText(self, wx.ID_ANY, _("add"))
        self.checkbox_5 = wx.CheckBox(self, wx.ID_ANY, _("Author"))
        self.checkbox_6 = wx.CheckBox(self, wx.ID_ANY, _("isbn"))
        self.checkbox_7 = wx.CheckBox(self, wx.ID_ANY, _("date(year,month)"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Suggest Names"))
        self.button_3 = wx.Button(self, wx.ID_ANY, _("Rename All Files Marked Green"))
        self.radios_add = [self.radio_btn_2, self.radio_btn_3]
        self.radios_remove = [self.radio_btn_4, self.radio_btn_5, self.radio_btn_6]

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ReName.__set_properties
        self.SetSize((758, 535))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ReName.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.label_1, 0, 0, 0)
        sizer_7.Add(self.checkbox_1, 0, 0, 0)
        sizer_7.Add(self.checkbox_2, 0, 0, 0)
        sizer_7.Add(self.checkbox_3, 0, 0, 0)
        sizer_7.Add(self.checkbox_4, 0, 0, 0)
        sizer_6.Add(sizer_7, 0, 0, 0)
        sizer_8.Add(self.label_2, 0, 0, 0)
        sizer_8.Add(self.text_ctrl_6, 0, 0, 0)
        sizer_8.Add(self.label_3, 0, 0, 0)
        sizer_8.Add(self.radio_btn_2, 0, 0, 0)
        sizer_8.Add(self.radio_btn_3, 0, 0, 0)
        sizer_6.Add(sizer_8, 0, 0, 0)
        sizer_9.Add(self.label_4, 0, 0, 0)
        sizer_9.Add(self.text_ctrl_7, 0, 0, 0)
        sizer_9.Add(self.label_5, 0, 0, 0)
        sizer_9.Add(self.radio_btn_4, 0, 0, 0)
        sizer_9.Add(self.radio_btn_5, 0, 0, 0)
        sizer_9.Add(self.radio_btn_6, 0, 0, 0)
        sizer_6.Add(sizer_9, 0, 0, 0)
        sizer_10.Add(self.label_6, 0, 0, 0)
        sizer_10.Add(self.checkbox_5, 0, 0, 0)
        sizer_10.Add(self.checkbox_6, 0, 0, 0)
        sizer_10.Add(self.checkbox_7, 0, 0, 0)
        sizer_6.Add(sizer_10, 0, 0, 0)
        sizer_11.Add(self.button_2, 0, 0, 0)
        sizer_11.Add(self.button_3, 0, 0, 0)
        sizer_6.Add(sizer_11, 0, 0, 0)
        sizer_3.Add(sizer_6, 1, 0, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

    def setRename(self, add_text, remove_text, add_to, remove_from,
            add_author, add_isbn, add_date):
        if add_to > len(self.radios_add):
            print "WARNING! Rename:add_to too large"
        else:
            self.radios_add[add_to-1].SetValue(True)

        if remove_from > len(self.radios_remove):
            print "WARNING! Rename:remove_from too large"
        else:
            self.radios_remove[remove_from-1].SetValue(True)

        self.text_ctrl_6.SetValue(add_text)
        self.text_ctrl_7.SetValue(remove_text)
        self.checkbox_5.SetValue(add_author)
        self.checkbox_6.SetValue(add_isbn)
        self.checkbox_7.SetValue(add_date)

    def _get_radio_checked(self, lists):
        for index, obj in enumerate(lists):
            if obj.GetValue():
                return index+1  # we count start from 1 instead of 0
        print "Something wrong in getExtractTo(). Should not reach here"
        return 1

    def getRename(self):
        add_to = self._get_radio_checked(self.radios_add)
        remove_from = self._get_radio_checked(self.radios_remove)
        add_text = self.text_ctrl_6.GetValue()
        remove_text = self.text_ctrl_7.GetValue()
        add_author = self.checkbox_5.GetValue()
        add_isbn = self.checkbox_6.GetValue()
        add_date = self.checkbox_7.GetValue()
        return (add_text, remove_text, add_to, remove_from, add_author, add_isbn, add_date)


# end of class ReName
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        config = ReName(None, wx.ID_ANY, "")
        self.SetTopWindow(config)
        config.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    gettext.install("BookMateConfig") # replace with the appropriate catalog name

    BookMateConfig = MyApp(0)
    BookMateConfig.MainLoop()
